### ISSUE TITLE
Error when resolving entities/properties

### ISSUE THREAD

**Issue by sfeng88** [v5analytics/visallo#125]
Steps to reproduce:
1) Make sure you have justification verification turned on
2) Resolve text to a property or entity

Error:
![screen shot 2015-05-19 at 3 33 15 pm](https://cloud.githubusercontent.com/assets/4804560/7712008/754ff1a0-fe3c-11e4-98d5-843bb73a6743.png)

UI doesn't have a field for justification when resolving text
![screen shot 2015-05-19 at 3 34 56 pm](https://cloud.githubusercontent.com/assets/4804560/7712035/a305426c-fe3c-11e4-9f77-5546cd0e6495.png)

**Comment by srfarley** [comment]
fixed: https://github.com/v5analytics/visallo/commit/a6301600181934b8d0e0e6d7d43169fd793c188a
