### ISSUE TITLE
Change alternate right-click keyboard combo to alt-click

### ISSUE THREAD

**Issue by kunklejr** [v5analytics/visallo#132]
The current keyboard combination is ctrl-click, but that's also the intuitive combo for selecting and deselecting multiple things in a search results list, on the graph, on a map, etc.

**Comment by jharwig** [comment]
I'll have to think about this one more. The Mac is implementing the ctrl+click == context menu, not visallo. The mac also uses CMD as the key to add/remove selection, not CTRL.
