### ISSUE TITLE
Select Connected Entities shortcut broken

### ISSUE THREAD

**Issue by kunklejr** [v5analytics/visallo#169]

**Comment by nidasid** [comment]
Still doesn't work.

**Comment by jharwig** [comment]
https://github.com/v5analytics/visallo/pull/329

**Comment by nidasid** [comment]
@jharwig Does not work in IE11
[selecting-connected-not-work.zip](https://github.com/v5analytics/visallo/files/266138/selecting-connected-not-work.zip)

**Comment by nidasid** [comment]
Works fine now
