### ISSUE TITLE
Simultaneously selecting changes to publish and undo behaves unexpectedly

### ISSUE THREAD

**Issue by kunklejr** [v5analytics/visallo#174]

**Comment by nidasid** [comment]
Still occurring. The diff panel disappears and then reappears after a couple of seconds. I selected some to Undo and some to Publish, and first hit Undo, when the diff panel reappeared, everything I had selected to publish was no longer selected.

**Comment by EvanOxfeld** [comment]
https://github.com/v5analytics/visallo/pull/326

**Comment by nidasid** [comment]
Works fine now
