### ISSUE TITLE
Front End extensibility README missing documentation

### ISSUE THREAD

**Issue by kylerob** [v5analytics/visallo#175]
The [Front End README's](https://github.com/v5analytics/visallo/blob/master/docs/front-end.md) "Extensibility" section says to look at another README for more information:

> For more extensibility options, see README in the js/configuration/plugins directories.

Does this directory exist? I haven't been able to locate it.

**Comment by joeferner** [comment]
Hope this clarification helps

**Comment by kylerob** [comment]
Awesome thanks!
