### ISSUE TITLE
First install; mvn builds successful, jetty fails

### ISSUE THREAD

**Issue by Joshfindit** [v5analytics/visallo#179]
- Started with a fresh CentOS machine
- installed Oracle JDK 8, maven, and Docker
- allowed root in .bowerrc

```
Apache Maven 3.3.3 (7994120775791599e205a5524ec3e0dfe41d4a06; 2015-04-22T07:57:37-04:00)
Maven home: /usr/local/apache-maven/apache-maven-3.3.3
Java version: 1.8.0_65, vendor: Oracle Corporation
Java home: /usr/java/jdk1.8.0_65/jre
Default locale: en_CA, platform encoding: UTF-8
OS name: "linux", version: "3.10.0-229.14.1.el7.x86_64", arch: "amd64", family: "unix"
```
- `docker/build-dev.sh` (success)
- `mvn package -pl web/war -am -DskipTests -Dsource.skip=true` (came back successful, copied war file)
- `mvn package -pl ./web/plugins/auth-username-only -am -DskipTests` (came back successful, copied lib)
- `docker/run-dev.sh` (success)
- `/opt/jetty/bin/jetty.sh start` **fail**

From `2015_11_05.stderrout.log` ( http://pastebin.com/9zFaiRvz ) 
```
2015-11-05 21:58:44.807/UTC WARN  [:] [hadoop.util.NativeCodeLoader] Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
{buildNumber=d59973b3474e0ea4dd8a7bcbe88123565e6773f0-20150612151710, version=0.21.1, timestamp=1434147430641}
2015-11-05 21:59:02.856:WARN:oejw.WebAppContext:main: Failed startup of context o.e.j.w.WebAppContext@737996a0{/,file:/tmp/jetty-0.0.0.0-8080-root.war-_-any-7136200177818589901.dir/webapp/,STARTING}{/root.war}
org.visallo.core.exception.VisalloException: Could not startup context
	at org.visallo.web.ApplicationBootstrap.contextInitialized(ApplicationBootstrap.java:77)
```

**Comment by joeferner** [comment]
From looking at your log it looks like an ontology issue. You seem to be missing a concept with an intent of `entityImage`. Have you loaded an ontology using the instructions here: http://docs.visallo.org/running.html#deploy-an-ontology

Were you able to get the jetty server running the mvn command here: http://docs.visallo.org/running.html#run-the-web-application
