### ISSUE TITLE
Viewing a vertex/edge shouldn't always request ACL

### ISSUE THREAD

**Issue by jharwig** [v5analytics/visallo#185]
Every time a vertex or edge is opened in detail pane a `acl` request is made. We should cache the result per element on the front-end and add some web socket message that it should be invalidated.

The front-end caching is easy, but the notification might be difficult. Consider someone implementing a `ACLProvider` that checks the value of a vertex property to allow editing. The access control for that vertex should be reloaded if that property changes. A basic implementation might just re-request the ACL on any property/vertex change. But, that would create more requests than necessary.

**Comment by srfarley** [comment]
https://github.com/v5analytics/visallo/pull/440 should resolve this.
