### ISSUE TITLE
Don't require all image metadata intent properties

### ISSUE THREAD

**Issue by jharwig** [v5analytics/visallo#2]
The `ImageMetadataGraphPropertyWorker` currently requires all property intents to work. Make all optional and only fill in the ones that exist in ontology.

Required:

        fileSizeIri;
        dateTakenIri;
        deviceMakeIri;
        deviceModelIri;
        geoLocationIri;
        headingIri;
        metadataIri;
        widthIri;
        heightIri;

**Comment by joeferner** [comment]
Fixed: https://github.com/v5analytics/visallo/commit/f0d7975193c1d9502916c4d79e961c0e518bb022
