### ISSUE TITLE
Database Initialization - no DB directory under the Dev subdirectory : MVN build fails ..

### ISSUE THREAD

**Issue by profversaggi** [v5analytics/visallo#236]
I'm doing a new install of Visallo and per this page of the Docs:

http://docs.visallo.org/getting-started/build.html

You will need to create the necessary tables before using the default out-of-the-box embedded database. This can be done by running the following maven command from the $PROJECT_DIR directory.

  mvn -f **dev/db**/pom.xml sql:execute@create-db

Yet when I look in the Cloned Visallo dir under dev, there is no DB dir. I've also downloaded the ZIP file and checked there just in case, nothing there either ...

Any suggestions as to what is the best way to initialize the DB would be greatly appreciated.

Thank you in advance ...

**Comment by profversaggi** [comment]
Following the install directions in the documentation and watching them fail, reading the issues with the repository changes combined with the maven error messages about not being able to find critical jar files and other artifacts from the official repositories I can only conclude that this project is either in great disarray or DOA. If it is neither, I'd be appreciate knowing when the project will be updates to the point where it actually works as the directions say ....

**Comment by sfeng88** [comment]
Thank you for bringing this issue to our attention. I've gone ahead and updated the documentation to reflect recent changes we've made. Instead of asking a user to manually initialize the DB, we've built that feature into the newest release of simpleorm (https://github.com/v5analytics/simple-orm/commit/bc6b73d42ce47b3ec2808a8aca3b71f0169ec67f) that Visallo now depends on.

**Comment by profversaggi** [comment]
That is good news - so how does one actually go from a code install to a working instance? There was no clear direction in the documentation ?

**Comment by profversaggi** [comment]
UPDATE: 

As I attempted to run the web app I received similar results ...

**  mvn -am -pl dev/jetty-server -P dev-jetty-run compile**

[INFO] Reactor Summary:
[INFO]
[INFO] Visallo: Web: Client API .......................... SUCCESS [0.522s]
[INFO] Visallo ........................................... SUCCESS [0.294s]
[INFO] Visallo: Core Group ............................... SUCCESS [0.011s]
[INFO] Visallo: Core ..................................... SUCCESS [0.386s]
[INFO] Visallo: Common ................................... SUCCESS [0.011s]
[INFO] Visallo: Common: RDF .............................. SUCCESS [7.541s]
[INFO] Visallo: Messages ................................. SUCCESS [0.028s]
[INFO] Visallo: Core: Plugins ............................ SUCCESS [0.018s]
[INFO] Visallo: Core: Plugin: Model: Queue: InMemory ..... SUCCESS [0.099s]
[INFO] Visallo: Core: Plugin: Model: Vertexium ........... SUCCESS [0.259s]
[INFO] Visallo: Core: Plugin: Model: Vertexium Elasticsearch  SUCCESS [25.336s]
[INFO] Visallo: Core: Plugin: Model: Vertexium InMemory .. SUCCESS [0.038s]
[INFO] Visallo: Dev ...................................... SUCCESS [0.019s]
[INFO] Visallo: Web ...................................... SUCCESS [0.019s]
**[INFO] Visallo: Web: Base ................................ FAILURE [0.362s]**
[INFO] Visallo: Web: Server .............................. SKIPPED
[INFO] Visallo: Web: Server: Base ........................ SKIPPED
[INFO] Visallo: Web: Server: Jetty ....................... SKIPPED
[INFO] Visallo: Web: Plugin Base ......................... SKIPPED
[INFO] Visallo: Web: Plugin: Username-only Authentication  SKIPPED
[INFO] Visallo: Web: Plugin: Admin User Tools ............ SKIPPED
[INFO] Visallo: Web: Plugins: Admin Import RDF ........... SKIPPED
[INFO] Visallo: GraphPropertyWorker ...................... SKIPPED
[INFO] Visallo: GraphPropertyWorker: Plugin Test ......... SKIPPED
[INFO] Visallo: GraphPropertyWorker: Plugin Base ......... SKIPPED
[INFO] Visallo: GraphPropertyWorker: Plugin: E-Mail Address Extractor  SKIPPED
[INFO] Visallo: GraphPropertyWorker: Plugin: Mime Type Ontology Mapper  SKIPPED
[INFO] Visallo: GraphPropertyWorker: Plugin: Phone Number Extractor  SKIPPED
[INFO] Visallo: GraphPropertyWorker: Plugin: Tika Mime Type Mapper  SKIPPED
[INFO] Visallo: GraphPropertyWorker: Plugin: Tika Text Extractor  SKIPPED
[INFO] Visallo: GraphPropertyWorker: Plugin: Zip Code Extractor  SKIPPED
[INFO] Visallo: Web: War ................................. SKIPPED
[INFO] Visallo: Dev: Jetty Server ........................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 35.417s
[INFO] Finished at: Sat Mar 19 00:16:18 EDT 2016
[INFO] Final Memory: 48M/578M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project visallo-web: Could not resolve dependencies for project org.visallo:visallo-web:jar:1.1-SNAPSHOT: Failed to collect dependencies for [org.visallo:visallo-core:jar:1.1-SNAPSHOT (compile), org.visallo:visallo-messages:jar:1.1-SNAPSHOT (compile), org.visallo:visallo-model-vertexium-inmemory:jar:1.1-SNAPSHOT (compile), com.v5analytics.simpleorm:simple-orm-jetty-session-manager:jar:1.1.0 (provided), org.visallo:visallo-closure-compiler:jar:1.0.0 (compile), org.eclipse.jetty:jetty-server:jar:9.2.7.v20150116 (provided), org.eclipse.jetty:jetty-servlets:jar:9.2.7.v20150116 (compile), javax.servlet:javax.servlet-api:jar:3.1.0 (provided), com.v5analytics.webster:webster:jar:2.2.0 (compile), com.google.inject:guice:jar:3.0 (compile), org.atmosphere:atmosphere-annotations:jar:2.4.2 (compile), org.atmosphere:atmosphere-runtime:jar:2.4.2 (compile), org.json:json:jar:20131018 (compile), log4j:log4j:jar:1.2.17 (compile), commons-fileupload:commons-fileupload:jar:1.3.1 (compile), net.sf.uadetector:uadetector-resources:jar:2014.06 (compile), com.github.jknack:handlebars:jar:1.0.0 (compile), com.asual.lesscss:lesscss-engine:jar:1.3.3 (compile), org.reflections:reflections:jar:0.9.10 (compile), org.slf4j:slf4j-api:jar:1.7.10 (compile), org.hamcrest:hamcrest-library:jar:1.3 (test), junit:junit:jar:4.11 (test), org.mockito:mockito-core:jar:1.9.5 (test), org.powermock:powermock-api-mockito:jar:1.5.1 (test), org.powermock:powermock-module-junit4:jar:1.5.1 (test), net.sourceforge.cobertura:cobertura:jar:2.0.3 (test)]: Failed to read artifact descriptor for org.visallo:visallo-closure-compiler:jar:1.0.0: Could not transfer artifact org.visallo:visallo-closure-compiler:pom:1.0.0 from/to v5analytics (https://mvn.v5analytics.com/content/groups/org.visallo): peer not authenticated -> [Help 1]

**Comment by sfeng88** [comment]
I'm assuming you haven't seen my message on the google group (https://groups.google.com/d/msg/visallo/yNBgXQyCqhQ/f_kNa5cLBQAJ). 

We are having some issues with `mvn.v5analytics.com` which is the cause of the error you posted above. Please bear with us while we work to solve the error. We will post when "mvn.v5analytics.com" is back online.

**Comment by profversaggi** [comment]
I just read that - thank you for the update. Pls let me know when things are back up and running. Do you ahve any rough ideas of a time frame? A couple of days or longer?

**Comment by dsingley** [comment]
We've installed a new certificate for the Nexus server but it's also at a new URL, https://mvn.visallo.com/
The Visallo pom.xml files have been updated so please let us know if you continue to have any issues after pulling.

**Comment by profversaggi** [comment]
So how does the New URL get factored into the MVN process - should I modify the POM's to include that?

**Comment by dsingley** [comment]
I've already updated them in 21c5895b997843e75e96e41b770f3b054ade5854

**Comment by profversaggi** [comment]
Recon Report: - seems like the Web base is failing. It's barking about needing Maven V 3.1.0 for the  **com.github.eirslett:frontend-maven-plugin:0.0.28** plugin. I'm running 3.0.5. I'll check into that and see if that fixes things.



versaggi@visallo:~/visallo$ **mvn package -pl web/war -am -DskipTests -Dsource.skip=true**
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO]
[INFO] Visallo: Web: Client API
[INFO] Visallo
[INFO] Visallo: Core Group
[INFO] Visallo: Core
[INFO] Visallo: Messages
[INFO] Visallo: Core: Plugins
[INFO] Visallo: Core: Plugin: Model: Vertexium
[INFO] Visallo: Core: Plugin: Model: Vertexium InMemory
[INFO] Visallo: Web
[INFO] Visallo: Web: Base
[INFO] Visallo: Web: War

...
...
...

[INFO]
[INFO] --- buildnumber-maven-plugin:1.2:create (create-build-number) @ visallo-web ---
[INFO] Checking for local modifications: skipped.
[INFO] Updating project files from SCM: skipped.
[INFO] Executing: /bin/sh -c cd /home/versaggi/visallo/web/web-base && git rev-parse --verify HEAD
[INFO] Working directory: /home/versaggi/visallo/web/web-base
[INFO] Storing buildNumber: 21c5895b997843e75e96e41b770f3b054ade5854 at timestamp: 1458394536421
[INFO] Executing: /bin/sh -c cd /home/versaggi/visallo/web/web-base && git rev-parse --verify HEAD
[INFO] Working directory: /home/versaggi/visallo/web/web-base
[INFO] Storing buildScmBranch: UNKNOWN
[INFO]
[INFO] --- buildnumber-maven-plugin:1.2:create-timestamp (create-formatted-timestamp) @ visallo-web ---
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] Visallo: Web: Client API .......................... SUCCESS [2.653s]
[INFO] Visallo ........................................... SUCCESS [0.230s]
[INFO] Visallo: Core Group ............................... SUCCESS [0.021s]
[INFO] Visallo: Core ..................................... SUCCESS [3.046s]
[INFO] Visallo: Messages ................................. SUCCESS [0.044s]
[INFO] Visallo: Core: Plugins ............................ SUCCESS [0.017s]
[INFO] Visallo: Core: Plugin: Model: Vertexium ........... SUCCESS [0.701s]
[INFO] Visallo: Core: Plugin: Model: Vertexium InMemory .. SUCCESS [0.391s]
[INFO] Visallo: Web ...................................... SUCCESS [0.012s]
**[INFO] Visallo: Web: Base ................................ FAILURE [8.976s]**
[INFO] Visallo: Web: War ................................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 16.515s
[INFO] Finished at: Sat Mar 19 09:35:36 EDT 2016
[INFO] Final Memory: 53M/460M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:0.0.28:install-node-and-npm (install-node-and-npm) on project visallo-web:** The plugin com.github.eirslett:frontend-maven-plugin:0.0.28 requires Maven version 3.1.0 **-> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginIncompatibleException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :visallo-web

**Comment by profversaggi** [comment]
That worked! You guys are awesome! Thank you! :-)
