### ISSUE TITLE
root/pom.xml

### ISSUE THREAD

**Issue by innate-ideas** [v5analytics/visallo#248]
Elasticsearch version needs to be updated from version 1.4.4 to version 2.2.1.

**Comment by dsingley** [comment]
Was there a new feature you were looking forward to using?

**Comment by innate-ideas** [comment]
Sorry this was a poorly written issue. I encountered an issue with the download of all versions except 2.2.1,  it turned out to be a Suricata IDS rule was blocking the maven downloads. I'll close this.
