### ISSUE TITLE
unable to build visallo web war in latest master branch

### ISSUE THREAD

**Issue by ashitabh** [v5analytics/visallo#304]
Need help to build/run Visallo. I am getting the following error while running
mvn -am -pl dev/jetty-server -P dev-jetty-run compile

[INFO] Reactor Summary:
[INFO]
[INFO] Visallo: Web: Client API ........................... SUCCESS [ 14.617 s]
[INFO] Visallo ............................................ SUCCESS [  1.413 s]
[INFO] Visallo: Core Group ................................ SUCCESS [  0.601 s]
[INFO] Visallo: Core ...................................... SUCCESS [ 33.645 s]
[INFO] Visallo: Messages .................................. SUCCESS [  0.413 s]
[INFO] Visallo: Core: Plugins ............................. SUCCESS [  0.257 s]
[INFO] Visallo: Core: Plugin: Model: Vertexium ............ SUCCESS [  4.964 s]
[INFO] Visallo: Core: Plugin: Model: Vertexium InMemory ... SUCCESS [  5.352 s]
[INFO] Visallo: Web ....................................... SUCCESS [  0.111 s]
[INFO] Visallo: Web: Base ................................. SUCCESS [ 28.588 s]
[INFO] Visallo: Web: War .................................. FAILURE [ 31.910 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 02:03 min
[INFO] Finished at: 2016-04-30T17:04:09+05:30
[INFO] Final Memory: 45M/508M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:0.0.28:grunt (grunt) on project visallo-web-war: Failed to run task: 'grunt development' failed. (error code 6) -> [Help 1]

**Comment by srfarley** [comment]
Do you see any errors prior to this output? Also, what operating system are you using?

**Comment by ashitabh** [comment]
Its Linux CentOS 6 .
The error seems to be with grunt execution, which I removed and able to create visallo-web-war-1.1-SNAPSHOT.war

 <execution>
                                <id>grunt</id>
                                <goals>
                                    <goal>grunt</goal>
                                </goals>
                                <configuration>
                                    <arguments>${grunt.target}</arguments>
                                </configuration>
                            </execution>

The Error message as I said is just 1 liner 
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:0.0.28:grunt (grunt) on project visallo-web-war: Failed to run task: 'grunt development' failed. (error code 6) -> [Help 1]

what exactly the above execution statement do?

**Comment by ashitabh** [comment]
[visallo.log.txt](https://github.com/v5analytics/visallo/files/243600/visallo.log.txt)
pls find attached debug mode log

**Comment by ashitabh** [comment]
OK, so after removing grunt execution task, visallo web war file is created and web server started . however , I see just a visallo logo on first page at https://local host:8889 and nothing else , no login text box , no hyperlink... Just visallo icon/image at the center of web page

**Comment by srfarley** [comment]
`grunt` does need to run because that's what compiles the JavaScript. That's why you see only the loading page. Can you please run `find . -name grunt` from the root `visallo` directory and paste the result here?

**Comment by ashitabh** [comment]
sure, here is the output
[xxx@xxx visallo]# find . -name grunt
./web/war/src/main/webapp/node_modules/grunt-cli/bin/grunt
./web/war/src/main/webapp/node_modules/.bin/grunt
./web/war/src/main/webapp/node_modules/bootstrap-datepicker/grunt
./web/war/src/main/webapp/node_modules/grunt
./web/war/src/main/webapp/node_modules/grunt/lib/grunt

**Comment by srfarley** [comment]
Thanks. Now try this:
`cd web/war/src/main/webapp`
`grunt development`

**Comment by srfarley** [comment]
Sorry, that should have been:
`cd web/war/src/main/webapp`
`./node_modules/.bin/grunt development`

**Comment by ashitabh** [comment]
webapp]# ./node_modules/.bin/grunt development
(node:27096) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
Running "clean:src" (clean) task
>> 0 paths cleaned.

Running "eslint:development" (eslint) task


Running "less:development" (less) task
>> FileError: '../libs/bootstrap/less/bootstrap.less' wasn't found. Tried - libs/bootstrap/less/bootstrap.less,libs/bootstrap/less/bootstrap.less,../libs/bootstrap/less/bootstrap.less in less/visallo.less on line 29, column 1:
>> 28 // Import bootstrap
>> 29 @import "../libs/bootstrap/less/bootstrap.less";
>> 30 #grid {
Warning: Error compiling less/visallo.less Use --force to continue.

Aborted due to warnings.

**Comment by srfarley** [comment]
Do you have a `web/war/src/main/webapp/libs` directory?

**Comment by ashitabh** [comment]
no, it's not there .
please let me know the next step

**Comment by srfarley** [comment]
It sounds like NPM module installation failed. Try `~/.m2/repository/node/v4.2.1/node/npm install` from the `web/war/src/main/webapp` directory.

**Comment by ashitabh** [comment]
webapp]# ~/.m2/repository/node/v4.2.1/node/npm install
(node:32122) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
npm WARN engine fsevents@1.0.12: wanted: {"node":">=0.8.0"} (current: {"node":"6.0.0-pre","npm":"3.3.8"})
npm WARN install Couldn't install optional dependency: Unsupported
npm WARN lifecycle visallo@0.1.0~postinstall: cannot run in wd %s %s (wd=%s) visallo@0.1.0 grunt deps /app/visallo/web/war/src/main/webapp

**Comment by srfarley** [comment]
There might be system-installed versions of the front-end tools that are being used instead of the ones the Visallo build installs locally. Check with:
`which node`
`which npm`
`which grunt`

**Comment by ashitabh** [comment]
[root@bangvmplCIID01 webapp]# which node
/usr/local/bin/node
[root@bangvmplCIID01 webapp]# which npm
/usr/local/bin/npm
[root@bangvmplCIID01 webapp]# which grunt
/usr/local/bin/grunt

**Comment by srfarley** [comment]
OK, let's try another way. We have a `Makefile` in `web/war/src/main/webapp` which definitely uses the tools installed by the build. From `web/war/src/main/webapp`, run:
`make clean`
`make`

**Comment by ashitabh** [comment]
make output 


Running "clean:src" (clean) task
>> 0 paths cleaned.

Running "eslint:development" (eslint) task


Running "less:development" (less) task
>> FileError: '../libs/bootstrap/less/bootstrap.less' wasn't found. Tried - 

libs/bootstrap/less/bootstrap.less,libs/bootstrap/less/bootstrap.less,../libs/bootstrap/less/bootstrap.less in less/visallo.less on line 29, column 1:
>> 28 // Import bootstrap
>> 29 @import "../libs/bootstrap/less/bootstrap.less";
>> 30 #grid {
Warning: Error compiling less/visallo.less Use --force to continue.

Aborted due to warnings.
make: *** [all] Error 6

**Comment by srfarley** [comment]
I'm not sure what's going on here. Do you have either `node_modules` or `libs` under `web/war/src/main/webapp`?

**Comment by ashitabh** [comment]
yes, /app/visallo/web/war/src/main/webapp/node_modules/ exists

**Comment by ashitabh** [comment]
who creates this file ../libs/bootstrap/less/bootstrap.less ??

**Comment by genofuzzy** [comment]
Hello.  Just a little trick waiting the fix: just copy content of
node_modules to missing libs and...  it works.

Il Sab 30 Apr 2016 16:33 ashitabh <notifications@github.com> ha scritto:

**Comment by srfarley** [comment]
@genofuzzy  Thanks, that's a good work-around for now.
@ashitabh  To answer your question, `webapp/grunt-tasks/copy-frontend-dependencies.js` copies the dependencies from `node_modules` to `libs`.

**Comment by ashitabh** [comment]
thank you very much
it worked finally 
I am able to login now 
closing the ticket 
once again , lot of thanks :)

**Comment by genofuzzy** [comment]
Hello.  Just a trick waiting the fix.  You can copy content of node_modules
in the missing libs
Il 30/Apr/2016 16:33, "ashitabh" <notifications@github.com> ha scritto:

**Comment by srfarley** [comment]
@ashitabh Good to hear! We think we found the problem. We'll work on a fix.

**Comment by genofuzzy** [comment]
My apologies: I was out of connection and so I sent the message twice!  :-(
Il 30/Apr/2016 06:16 PM, "Steven Farley" <notifications@github.com> ha
scritto:
