### ISSUE TITLE
Visallo data ingestion automation

### ISSUE THREAD

**Issue by ashitabh** [v5analytics/visallo#308]
I have to automate data ingestion . Do you have a step-by-step document to explain this?
Lumify.io has a sample project named foodtruck to consume twitter data , do you have something similar to it?

**Comment by srfarley** [comment]
The easiest way to ingest data for open-source Visallo is to use RDF Import: https://github.com/v5analytics/visallo/tree/master/tools/rdf-import

**Comment by ashitabh** [comment]
Thanks
