### ISSUE TITLE
Need an effective localization approach

### ISSUE THREAD

**Issue by yhmo** [v5analytics/visallo#693]
Hi Visallo team,

The Visallo is a great tool for visualization analysis,  we want to make a local version by our language. but when I try to do it, I found the ui strings are placed in different folder/files, it is hard to ensure all strings are translated. I noticed the ui strings are mainly in two files:
/visallo/core/core/src/main/resources/MessageBundle.properties
/visallo/core/core-test/src/test/resources/org/visallo/core/formula/configuration.json

But there are some strings are scattered in .owl files and .js files, such as:
/visallo/config/ontology-minimal/minimal.owl
/visallo/web/war/src/main/webapp/js/dashboard/registerDefaultItems.js

So I think there should be a centralized file to hold all ui strings. An easy localization approach can help Visallo expand to more countries.

**Comment by jharwig** [comment]
It's a bug that some of the strings in `registerDefaultItems` aren't using i18n strings. I'll add an issue for that.

All strings in the core open-source project are(/should be) in `/visallo/core/core/src/main/resources/MessageBundle.properties`. The other file is a test file that isn't used other than in unit tests.

Plugins could also have their own MessageBundle.properties.

So, you can create a language web-plugin that calls `registerResourceBundle` in its WebAppPlugin class with the locale in the filename (ex: MessageBundle-fr.properties for french). There also isn't a user-exposed way to switch the language, but you can set the locale using the js console `switchLanguage('fr')`. A Webapp plugin could also be created to expose this to a user.

We don't bundle any languages other than the default currently.
