### ISSUE TITLE
Yarn error....please help :(

### ISSUE THREAD

**Issue by lorenzoromani1983** [v5analytics/visallo#835]

**Comment by lorenzoromani1983** [comment]
NB: prior to get the message above, this is what i get:

[INFO] Unpacking C:\Users\Lorenzo Romani\.m2\repository\com\github\eirslett\yarn\0.17.10\yarn-0.17.10.\yarn-0.17.10.msi into C:\Users\Lorenzo Romani\.m2\repository\node\v6.2.0\node\yarn
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] Visallo: Web: Client API ........................... SUCCESS [  8.572 s]
[INFO] Visallo ............................................ SUCCESS [  4.946 s]
[INFO] Visallo: Core Group ................................ SUCCESS [  0.516 s]
[INFO] Visallo: Core ...................................... SUCCESS [  7.764 s]
[INFO] Visallo: Common .................................... SUCCESS [  0.688 s]
[INFO] Visallo: Common: RDF ............................... SUCCESS [  1.333 s]
[INFO] Visallo: Core: Plugins ............................. SUCCESS [  0.531 s]
[INFO] Visallo: Core: Plugin: Model: Queue: InMemory ...... SUCCESS [  1.008 s]
[INFO] Visallo: Core: Plugin: Model: Vertexium ............ SUCCESS [  7.150 s]
[INFO] Visallo: Core: Plugin: Model: Vertexium InMemory ... SUCCESS [  1.408 s]
[INFO] Visallo: Core Test ................................. SUCCESS [  1.342 s]
[INFO] Visallo: Core: Plugin: Model: Vertexium Elasticsearch SUCCESS [  2.334 s]
[INFO] Visallo: Dev ....................................... SUCCESS [  1.073 s]
[INFO] Visallo: Web ....................................... SUCCESS [  0.546 s]
[INFO] Visallo: Web: Base ................................. FAILURE [ 16.714 s]
[INFO] Visallo: Web: Server ............................... SKIPPED
[INFO] Visallo: Web: Server: Base ......................... SKIPPED
[INFO] Visallo: Web: Server: Jetty ........................ SKIPPED
[INFO] Visallo: Web: Plugin Base .......................... SKIPPED
[INFO] Visallo: Web: Plugin: Username-only Authentication . SKIPPED
[INFO] Visallo: Web: Plugin: Admin User Tools ............. SKIPPED
[INFO] Visallo: Web: Plugin: Admin User Tools: User Property Authorization SKIPPED
[INFO] Visallo: Web: Plugin: Admin User Tools: User Property Privileges SKIPPED
[INFO] Visallo: Web: Plugins: Admin Import RDF ............ SKIPPED
[INFO] Visallo: Web: Plugin: Graph Work Product ........... SKIPPED
[INFO] Visallo: Web: Plugin: Map Work Product ............. SKIPPED
[INFO] Visallo: GraphPropertyWorker ....................... SKIPPED
[INFO] Visallo: GraphPropertyWorker: Plugin Base .......... SKIPPED
[INFO] Visallo: GraphPropertyWorker: Plugin: E-Mail Address Extractor SKIPPED
[INFO] Visallo: GraphPropertyWorker: Plugin: Mime Type Ontology Mapper SKIPPED
[INFO] Visallo: GraphPropertyWorker: Plugin: Phone Number Extractor SKIPPED
[INFO] Visallo: GraphPropertyWorker: Plugin: Tika Mime Type Mapper SKIPPED
[INFO] Visallo: GraphPropertyWorker: Plugin: Tika Text Extractor SKIPPED
[INFO] Visallo: GraphPropertyWorker: Plugin: Zip Code Extractor SKIPPED
[INFO] Visallo: Web: War .................................. SKIPPED
[INFO] Visallo: Dev: Jetty Server ......................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------

**Comment by fuzzydet** [comment]
Hello,  try to delete yarn.lock file before compiling.  The file is located in ~/web/war/src/main/webapp/ dir....

**Comment by lorenzoromani1983** [comment]
Thanks. But still doesn't work. Yarn keeps crushing my installation attempts, even on Mac OS.
Infact, now it stops here:

[INFO] ------------------------------------------------------------------------
[INFO] Building Visallo: Web: Plugin: Graph Work Product 3.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-enforcer-plugin:1.0:enforce (enforce-maven) @ visallo-web-product-graph ---
[INFO] 
[INFO] --- buildnumber-maven-plugin:1.2:create (create-build-number) @ visallo-web-product-graph ---
[INFO] Checking for local modifications: skipped.
[INFO] Updating project files from SCM: skipped.
[INFO] Executing: /bin/sh -c cd /Users/lorenzo/visallo/web/plugins/graph-product && git rev-parse --verify HEAD
[INFO] Working directory: /Users/lorenzo/visallo/web/plugins/graph-product
[INFO] Storing buildNumber: 5cfe2c318d6768f1108fe7c1255260e44c748bf0 at timestamp: 1482145489074
[INFO] Executing: /bin/sh -c cd /Users/lorenzo/visallo/web/plugins/graph-product && git rev-parse --verify HEAD
[INFO] Working directory: /Users/lorenzo/visallo/web/plugins/graph-product
[INFO] Storing buildScmBranch: UNKNOWN
[INFO] 
[INFO] --- buildnumber-maven-plugin:1.2:create-timestamp (create-formatted-timestamp) @ visallo-web-product-graph ---
[INFO] 
[INFO] --- frontend-maven-plugin:1.2:install-node-and-yarn (install-node-and-yarn) @ visallo-web-product-graph ---
[INFO] Node v6.2.0 is already installed.
[INFO] Yarn 0.17.10 was installed, but we need version v0.17.10
[INFO] Installing Yarn version v0.17.10
[INFO] Unpacking /Users/lorenzo/.m2/repository/com/github/eirslett/yarn/0.17.10/yarn-0.17.10./yarn-v0.17.10.tar.gz into /Users/lorenzo/.m2/repository/node/v6.2.0/node/yarn
[INFO] Installed Yarn locally.
[INFO] 
[INFO] --- frontend-maven-plugin:1.2:yarn (yarn install) @ visallo-web-product-graph ---
[INFO] Running 'yarn ' in /Users/lorenzo/visallo/web/plugins/graph-product/src/main/resources/org/visallo/web/product/graph
[INFO] yarn install v0.17.10
[INFO] [1/4] Resolving packages...
[INFO] [2/4] Fetching packages...


No error messages, but it just stops there.  :-( HATE YARN!

**Comment by joeybrk372** [comment]
Those logs look like normal operation. Can you try hitting the webserver at localhost:8888?

**Comment by lorenzoromani1983** [comment]
OMG...it worked! Thank you! i thought it would give some kind of "installation finalized" message. So  there won't be a quick launch icon? :)
