### ISSUE TITLE
Multi-click the entity quickly click error

### ISSUE THREAD

**Issue by Samli514006030** [v5analytics/visallo#860]
Ctrl + multi-select entities, when the number of entities over a certain limit, for example, 5, hold down the ctrl not released, the left mouse button click on the entity, the console will continue error, as is the data with visRate.js get visalloDate data problems , Will be how to solve specific?

**Comment by jharwig** [comment]
Those errors are for the element inspector display that was cancelled because the user made a new selection before they were loaded. They should be changed to warnings instead of errors.
