### ISSUE TITLE
Ctrl + entity positive and negative elections

### ISSUE THREAD

**Issue by Samli514006030** [v5analytics/visallo#861]
Hold down ctrl (shift or meta) to select multiple entities and edges, but press ctrl (shift or meta) again to click the selected edge, you can cancel the selection, but click on the entity can not. Read the code, is the graph graph in the graphFree function distance <5 lead to the problem, why should set distance <5 this logic? Not very understanding, please inform. Thank you

**Comment by jharwig** [comment]
Found an issue with undoing the last selected item. But you are referencing code from the graph before 3.0 which was released last fall.
