### ISSUE TITLE
Unable to compile and run the web application: Failed to run task: 'yarn ' failed.

### ISSUE THREAD

**Issue by JackieAnxis** [v5analytics/visallo#882]
I compiled visallo web application with the command provided in docs: 
`mvn -am -pl dev/jetty-server -P dev-jetty-run compile`,
however, failed with these infomation:

[INFO] Reactor Summary:
[INFO]
[INFO] Visallo: Web: Client API ........................... SUCCESS [  2.409 s]
[INFO] Visallo ............................................ SUCCESS [  1.744 s]
[INFO] Visallo: Core Group ................................ SUCCESS [  0.481 s]
[INFO] Visallo: Core ...................................... SUCCESS [  2.611 s]
[INFO] Visallo: Common .................................... SUCCESS [  0.274 s]
[INFO] Visallo: Common: RDF ............................... SUCCESS [  0.598 s]
[INFO] Visallo: Core: Plugins ............................. SUCCESS [  0.267 s]
[INFO] Visallo: Core: Plugin: Model: Queue: InMemory ...... SUCCESS [  0.588 s]
[INFO] Visallo: Core: Plugin: Model: Vertexium ............ SUCCESS [  2.380 s]
[INFO] Visallo: Core: Plugin: Model: Vertexium InMemory ... SUCCESS [  1.255 s]
[INFO] Visallo: Core Test ................................. SUCCESS [  0.514 s]
[INFO] Visallo: Core: Plugin: Model: Vertexium Elasticsearch SUCCESS [  1.283 s]
[INFO] Visallo: Dev ....................................... SUCCESS [  0.293 s]
[INFO] Visallo: Web ....................................... SUCCESS [  0.459 s]
[INFO] Visallo: Web: Base ................................. SUCCESS [  2.611 s]
[INFO] Visallo: Web: Server ............................... SUCCESS [  0.555 s]
[INFO] Visallo: Web: Server: Base ......................... SUCCESS [  0.725 s]
[INFO] Visallo: Web: Server: Jetty ........................ SUCCESS [  1.057 s]
[INFO] Visallo: Web: Plugin Base .......................... SUCCESS [  1.967 s]
[INFO] Visallo: Web: Plugin: Username-only Authentication . SUCCESS [  2.046 s]
[INFO] Visallo: Web: Plugin: Admin User Tools ............. SUCCESS [  2.312 s]
[INFO] Visallo: Web: Plugin: Admin User Tools: User Property Authorization SUCCESS [  2.082 s]
[INFO] Visallo: Web: Plugin: Admin User Tools: User Property Privileges SUCCESS [  1.485 s]
[INFO] Visallo: Web: Plugins: Admin Import RDF ............ SUCCESS [  1.662 s]
[INFO] Visallo: Web: Plugin: Graph Work Product ........... SUCCESS [ 34.546 s]
[INFO] Visallo: Web: Plugin: Map Work Product ............. SUCCESS [ 15.790 s]
[INFO] Visallo: GraphPropertyWorker ....................... SUCCESS [  0.397 s]
[INFO] Visallo: GraphPropertyWorker: Plugin Base .......... SUCCESS [  0.479 s]
[INFO] Visallo: GraphPropertyWorker: Plugin: E-Mail Address Extractor SUCCESS [  0.391 s]
[INFO] Visallo: GraphPropertyWorker: Plugin: Mime Type Ontology Mapper SUCCESS [  0.386 s]
[INFO] Visallo: GraphPropertyWorker: Plugin: Phone Number Extractor SUCCESS [  0.330 s]
[INFO] Visallo: GraphPropertyWorker: Plugin: Tika Mime Type Mapper SUCCESS [  1.542 s]
[INFO] Visallo: GraphPropertyWorker: Plugin: Tika Text Extractor SUCCESS [  1.508 s]
[INFO] Visallo: GraphPropertyWorker: Plugin: Zip Code Extractor SUCCESS [  0.725 s]
[INFO] Visallo: Web: War .................................. FAILURE [  3.049 s]
[INFO] Visallo: Dev: Jetty Server ......................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:34 min
[INFO] Finished at: 2017-01-15T14:20:05+08:00
[INFO] Final Memory: 53M/745M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.3:yarn (yarn install) on project visallo-web-war: Failed to run task: 'yarn ' failed. (error code 1) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :visallo-web-war

**Comment by smwesige** [comment]
I have the same problem. I have been trying to build for the past two days in vain

**Comment by JackieAnxis** [comment]
@smwesige Did you solve the problem?

**Comment by smwesige** [comment]
I put it on hold. I am going to try again and give you feedback. Thanks

**Comment by EvanOxfeld** [comment]
Thanks for reporting this issue. @JackieAnxis and @smwesige, do either of you have a `yarn-error.log` in `web/war/src/main/webapp`?

**Comment by smwesige** [comment]
Yes the yarn error is in web/war/src/main/webapp?

On Jan 17, 2017 18:16, "Evan Oxfeld" <notifications@github.com> wrote:

Thanks for reporting this issue. @JackieAnxis
<https://github.com/JackieAnxis> and @smwesige <https://github.com/smwesige>,
do either of you have a yarn-error.log in web/war/src/main/webapp?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/v5analytics/visallo/issues/882#issuecomment-273197222>,
or mute the thread

**Comment by bcanseco** [comment]
https://github.com/v5analytics/visallo/commit/2676fc1f30b86fd3759b535ebbca6f0600a0d52a fixed this issue for me on Windows 10 64bit. Would recommend you guys rebuild and see if it does for you too!

**Comment by JackieAnxis** [comment]
@bcanseco Thank you very much, your generosity has helped me a lot. Now it's Chinese new year, yeah! Happy new year! Thanks a lot, I have fixed it.
